# Generated by Django 5.2 on 2026-04-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformTrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_label', models.CharField(choices=[('CompleteUniform', 'Complete Uniform'), ('UniformTop', 'Uniform Top'), ('UniformPants', 'Uniform Pants'), ('NeedsReview', 'Needs Review')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=api.models.training_sample_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uniform_training_samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
