# Generated by Django 5.2 on 2026-06-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uniformtrainingsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentCode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
